# This is a basic workflow to help you get started with Actions

name: Copy README

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    paths:
      - 'README.md'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy README
        run: cp README.md docs/
      - name: Commit README
        run: |
          git config --global user.name 'Oliver Broomhall'
          git config --global user.email 'obroomhall@gmail.com'
          git commit -am "Copy README"
          git push
